// Code generated by protoc-gen-go. DO NOT EDIT.
// source: twallet/service.proto

package Twallet

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//请求注册服务
type ReqRegService struct {
	ServerId             *int32   `protobuf:"varint,1,opt,name=serverId" json:"serverId,omitempty"`
	SvrType              *int32   `protobuf:"varint,2,opt,name=svrType" json:"svrType,omitempty"`
	Host                 *string  `protobuf:"bytes,3,opt,name=host" json:"host,omitempty"`
	Port                 *int32   `protobuf:"varint,4,opt,name=port" json:"port,omitempty"`
	RoomId               *int32   `protobuf:"varint,5,opt,name=roomId" json:"roomId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqRegService) Reset()         { *m = ReqRegService{} }
func (m *ReqRegService) String() string { return proto.CompactTextString(m) }
func (*ReqRegService) ProtoMessage()    {}
func (*ReqRegService) Descriptor() ([]byte, []int) {
	return fileDescriptor_be001a42d87b0502, []int{0}
}

func (m *ReqRegService) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqRegService.Unmarshal(m, b)
}
func (m *ReqRegService) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqRegService.Marshal(b, m, deterministic)
}
func (m *ReqRegService) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqRegService.Merge(m, src)
}
func (m *ReqRegService) XXX_Size() int {
	return xxx_messageInfo_ReqRegService.Size(m)
}
func (m *ReqRegService) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqRegService.DiscardUnknown(m)
}

var xxx_messageInfo_ReqRegService proto.InternalMessageInfo

func (m *ReqRegService) GetServerId() int32 {
	if m != nil && m.ServerId != nil {
		return *m.ServerId
	}
	return 0
}

func (m *ReqRegService) GetSvrType() int32 {
	if m != nil && m.SvrType != nil {
		return *m.SvrType
	}
	return 0
}

func (m *ReqRegService) GetHost() string {
	if m != nil && m.Host != nil {
		return *m.Host
	}
	return ""
}

func (m *ReqRegService) GetPort() int32 {
	if m != nil && m.Port != nil {
		return *m.Port
	}
	return 0
}

func (m *ReqRegService) GetRoomId() int32 {
	if m != nil && m.RoomId != nil {
		return *m.RoomId
	}
	return 0
}

//响应注册服务
type AckRegService struct {
	Result               *int32   `protobuf:"zigzag32,1,opt,name=result" json:"result,omitempty"`
	ServerId             *int32   `protobuf:"varint,2,opt,name=serverId" json:"serverId,omitempty"`
	Errmsg               *string  `protobuf:"bytes,3,opt,name=errmsg" json:"errmsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AckRegService) Reset()         { *m = AckRegService{} }
func (m *AckRegService) String() string { return proto.CompactTextString(m) }
func (*AckRegService) ProtoMessage()    {}
func (*AckRegService) Descriptor() ([]byte, []int) {
	return fileDescriptor_be001a42d87b0502, []int{1}
}

func (m *AckRegService) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AckRegService.Unmarshal(m, b)
}
func (m *AckRegService) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AckRegService.Marshal(b, m, deterministic)
}
func (m *AckRegService) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AckRegService.Merge(m, src)
}
func (m *AckRegService) XXX_Size() int {
	return xxx_messageInfo_AckRegService.Size(m)
}
func (m *AckRegService) XXX_DiscardUnknown() {
	xxx_messageInfo_AckRegService.DiscardUnknown(m)
}

var xxx_messageInfo_AckRegService proto.InternalMessageInfo

func (m *AckRegService) GetResult() int32 {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return 0
}

func (m *AckRegService) GetServerId() int32 {
	if m != nil && m.ServerId != nil {
		return *m.ServerId
	}
	return 0
}

func (m *AckRegService) GetErrmsg() string {
	if m != nil && m.Errmsg != nil {
		return *m.Errmsg
	}
	return ""
}

func init() {
	proto.RegisterType((*ReqRegService)(nil), "Twallet.ReqRegService")
	proto.RegisterType((*AckRegService)(nil), "Twallet.AckRegService")
}

func init() { proto.RegisterFile("twallet/service.proto", fileDescriptor_be001a42d87b0502) }

var fileDescriptor_be001a42d87b0502 = []byte{
	// 184 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x8e, 0xbf, 0x0e, 0x82, 0x30,
	0x10, 0x87, 0x53, 0xe4, 0x8f, 0x5e, 0xc2, 0x60, 0x13, 0x49, 0xe3, 0x44, 0x98, 0x98, 0xf4, 0x19,
	0x1c, 0x59, 0x2b, 0x9b, 0x93, 0x81, 0x0b, 0x1a, 0x21, 0xc5, 0x6b, 0xc5, 0xf8, 0x00, 0xbe, 0xb7,
	0xa1, 0x54, 0xa3, 0x6e, 0xf7, 0xfd, 0xee, 0x1b, 0x3e, 0x58, 0x99, 0xfb, 0xb1, 0x6d, 0xd1, 0x6c,
	0x35, 0xd2, 0x70, 0xae, 0x70, 0xd3, 0x93, 0x32, 0x8a, 0x47, 0xe5, 0x34, 0x67, 0x4f, 0x06, 0xb1,
	0xc4, 0xab, 0xc4, 0x66, 0x3f, 0x09, 0x7c, 0x0d, 0xf3, 0xd1, 0x45, 0x2a, 0x6a, 0xc1, 0x52, 0x96,
	0x07, 0xf2, 0xc3, 0x5c, 0x40, 0xa4, 0x07, 0x2a, 0x1f, 0x3d, 0x0a, 0xcf, 0xbe, 0xde, 0xc8, 0x39,
	0xf8, 0x27, 0xa5, 0x8d, 0x98, 0xa5, 0x2c, 0x5f, 0x48, 0x7b, 0x8f, 0x5b, 0xaf, 0xc8, 0x08, 0xdf,
	0xaa, 0xf6, 0xe6, 0x09, 0x84, 0xa4, 0x54, 0x57, 0xd4, 0x22, 0xb0, 0xab, 0xa3, 0xec, 0x00, 0xf1,
	0xae, 0xba, 0x7c, 0x65, 0x8c, 0x22, 0xea, 0x5b, 0x6b, 0x6c, 0xc4, 0x52, 0x3a, 0xfa, 0xc9, 0xf3,
	0xfe, 0xf2, 0x12, 0x08, 0x91, 0xa8, 0xd3, 0x8d, 0xcb, 0x70, 0xf4, 0x0a, 0x00, 0x00, 0xff, 0xff,
	0xba, 0x8b, 0x40, 0xfd, 0x05, 0x01, 0x00, 0x00,
}
